# Generated by Django 5.0.6 on 2024-08-30 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_type', models.IntegerField(choices=[(1, 'deposit'), (2, 'withdraw'), (3, 'loan'), (4, 'loan_paid')], null=True)),
                ('time_tamp', models.DateTimeField(auto_now_add=True)),
                ('loan_approved', models.BooleanField(default=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.bankaccountpersonal')),
            ],
            options={
                'ordering': ['time_tamp'],
            },
        ),
    ]
