# Generated by Django 5.0.6 on 2024-08-27 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='Transactions_type',
            new_name='Transaction_type',
        ),
    ]
