# Generated by Django 5.0.6 on 2024-08-18 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_brand_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='slug',
        ),
    ]
