# Generated by Django 5.1.1 on 2024-09-07 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_points_personalaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='points',
        ),
    ]
