# Generated by Django 5.1.1 on 2024-09-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalaccount',
            name='points',
            field=models.DecimalField(decimal_places=2, default=499.0, max_digits=6),
        ),
    ]
