# Generated by Django 5.0.6 on 2024-07-31 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskDescription',
            new_name='Task Description',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='taskTitle',
            new_name='Task Title',
        ),
    ]
