# Generated by Django 5.0.6 on 2024-08-01 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_model', '0002_rename_taskdescription_taskmodel_task_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Task Description',
            new_name='task_description',
        ),
        migrations.RenameField(
            model_name='taskmodel',
            old_name='Task Title',
            new_name='task_title',
        ),
    ]
