# Generated by Django 5.0.6 on 2024-08-01 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='category_name',
            new_name='Category Name',
        ),
    ]
