# Generated by Django 5.0.6 on 2024-08-01 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_category', '0002_rename_category_name_taskcategory_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskcategory',
            old_name='Category Name',
            new_name='category_name',
        ),
    ]
