# Generated by Django 5.1.1 on 2024-09-07 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_image', models.ImageField(upload_to='books/media/books_images/')),
                ('books_title', models.CharField(max_length=200)),
                ('books_descriptions', models.TextField()),
                ('books_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('books_quantity', models.PositiveBigIntegerField(default=1)),
                ('books_add_time', models.DateTimeField(auto_now_add=True)),
                ('books_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='books_categories.bookscategory')),
            ],
        ),
    ]
