# Generated by Django 5.1.1 on 2024-09-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_books_books_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='books_author_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
