# Generated by Django 5.1.1 on 2024-09-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_books_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='books_ISBN',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='books_image',
            field=models.ImageField(upload_to='books_images/'),
        ),
    ]
