# Generated by Django 5.0.6 on 2024-08-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_rename_comment_email_comment_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
