# Generated by Django 5.0.6 on 2024-08-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_car_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='car_quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
