# Generated by Django 5.0.6 on 2024-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_remove_car_car_quantity_order_car_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_quantity',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
