# Generated by Django 5.0.6 on 2024-08-19 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_car_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Order_time',
            new_name='OrderTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='car_quantity',
            new_name='quantity',
        ),
    ]
